create table if not exists public.raid_browser_memory (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  local_id bigint not null,
  kind text not null check (char_length(kind) <= 40),
  value text not null check (char_length(value) <= 1000),
  created_at_ms bigint not null,
  created_at timestamptz not null default now(),
  unique(user_id, local_id)
);

alter table public.raid_browser_memory enable row level security;

create policy "raid memory select own"
on public.raid_browser_memory for select
to authenticated
using (auth.uid() = user_id);

create policy "raid memory insert own"
on public.raid_browser_memory for insert
to authenticated
with check (auth.uid() = user_id);

create policy "raid memory update own"
on public.raid_browser_memory for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "raid memory delete own"
on public.raid_browser_memory for delete
to authenticated
using (auth.uid() = user_id);

create index if not exists raid_browser_memory_user_created_idx
on public.raid_browser_memory(user_id, created_at_ms desc);
