import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import type { ThemePalette } from '@/lib/theme';

export function HomeFeatureCards({theme,downloadsCount,onDownloads,onLibrary,onPrivacy}:{theme:ThemePalette;downloadsCount:number;onDownloads:()=>void;onLibrary:()=>void;onPrivacy:()=>void}){
  const card=(title:string,sub:string,onPress:()=>void,icon:keyof typeof Ionicons.glyphMap,accent:string)=><Pressable onPress={onPress} style={({pressed})=>[s.card,{backgroundColor:theme.surface,borderColor:theme.border},pressed&&s.press]}><View style={[s.icon,{backgroundColor:theme.surface2,borderColor:theme.border}]}><Ionicons name={icon} size={21} color={accent}/></View><View style={s.copy}><Text style={[s.title,{color:theme.text}]}>{title}</Text><Text style={[s.sub,{color:theme.muted}]}>{sub}</Text></View><Ionicons name="chevron-back" size={20} color={theme.muted}/></Pressable>;
  return <>
    <View style={s.row}>{card('التنزيلات',downloadsCount?`${downloadsCount} عناصر حديثة`:'إدارة ملفاتك',onDownloads,'cloud-download-outline',theme.accent)}{card('المفضلة','وصول سريع',onLibrary,'bookmark-outline','#D5B26D')}</View>
    <Pressable onPress={onPrivacy} style={({pressed})=>[s.privacy,{backgroundColor:theme.surface,borderColor:theme.border},pressed&&s.press]}><View style={[s.shield,{backgroundColor:theme.surface2,borderColor:theme.border}]}><Ionicons name="shield-checkmark-outline" size={23} color="#73B88B"/></View><View style={s.copy}><Text style={[s.privacyTitle,{color:theme.text}]}>حماية الخصوصية</Text><Text style={[s.privacySub,{color:theme.muted}]}>HTTPS وVPN وبيانات التصفح في مكان واحد</Text></View><Ionicons name="chevron-back" size={20} color={theme.muted}/></Pressable>
  </>;
}
const s=StyleSheet.create({row:{flexDirection:'row-reverse',gap:10},card:{flex:1,minHeight:104,borderRadius:24,borderWidth:1,padding:14,flexDirection:'row-reverse',alignItems:'center',gap:10},icon:{width:44,height:44,borderRadius:15,borderWidth:1,alignItems:'center',justifyContent:'center'},copy:{flex:1},title:{fontSize:14,fontWeight:'900',textAlign:'right'},sub:{fontSize:10,marginTop:4,textAlign:'right'},privacy:{minHeight:88,borderRadius:24,borderWidth:1,padding:14,flexDirection:'row-reverse',alignItems:'center',gap:11},shield:{width:46,height:46,borderRadius:15,borderWidth:1,alignItems:'center',justifyContent:'center'},privacyTitle:{fontSize:16,fontWeight:'900',textAlign:'right'},privacySub:{fontSize:11,marginTop:4,textAlign:'right'},press:{transform:[{scale:.985}],opacity:.84}});
