import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import type { ThemePalette } from '@/lib/theme';

export function HomeFeatureCards({theme,activeDownloads,completedDownloads,vpnConnected,tabsCount,onDownloads,onLibrary,onPrivacy}:{theme:ThemePalette;activeDownloads:number;completedDownloads:number;vpnConnected:boolean;tabsCount:number;onDownloads:()=>void;onLibrary:()=>void;onPrivacy:()=>void}){
  const card=(title:string,sub:string,onPress:()=>void,icon:keyof typeof Ionicons.glyphMap,accent:string)=><Pressable onPress={onPress} style={({pressed})=>[s.card,{backgroundColor:theme.surface,borderColor:theme.border},pressed&&s.press]}><View style={[s.icon,{backgroundColor:theme.surface2,borderColor:theme.border}]}><Ionicons name={icon} size={21} color={accent}/></View><View style={s.copy}><Text style={[s.title,{color:theme.text}]}>{title}</Text><Text style={[s.sub,{color:theme.muted}]}>{sub}</Text></View><Ionicons name="chevron-back" size={20} color={theme.muted}/></Pressable>;
  const downloadText=activeDownloads?`${activeDownloads} تنزيل نشط`:completedDownloads?`${completedDownloads} مكتمل مؤخرًا`:'جاهز للتنزيل';
  return <>
    <View style={s.row}>{card('التنزيلات',downloadText,onDownloads,activeDownloads?'cloud-download':'cloud-download-outline',theme.accent)}{card('المكتبة',tabsCount?`${tabsCount} تبويب مفتوح • مفضلة وسجل`:'المفضلة والسجل',onLibrary,'library-outline','#D5B26D')}</View>
    <Pressable onPress={onPrivacy} style={({pressed})=>[s.privacy,{backgroundColor:theme.surface,borderColor:theme.border},pressed&&s.press]}>
      <View style={[s.shield,{backgroundColor:theme.surface2,borderColor:theme.border}]}><Ionicons name={vpnConnected?'shield-checkmark':'shield-outline'} size={23} color={vpnConnected?'#73B88B':theme.accent}/></View>
      <View style={s.copy}><View style={s.privacyTitleRow}><Text style={[s.privacyTitle,{color:theme.text}]}>الحماية والخصوصية</Text><View style={[s.statePill,{backgroundColor:vpnConnected?'rgba(74,170,112,.14)':theme.surface2,borderColor:vpnConnected?'rgba(74,170,112,.3)':theme.border}]}><View style={[s.dot,{backgroundColor:vpnConnected?'#62C48A':theme.muted}]}/><Text style={[s.stateText,{color:vpnConnected?'#72CE98':theme.muted}]}>{vpnConnected?'VPN متصل':'VPN غير متصل'}</Text></View></View><Text style={[s.privacySub,{color:theme.muted}]}>{vpnConnected?'النفق فعّال الآن • افتح لوحة الخصوصية للتفاصيل':'حالة صريحة بلا حماية وهمية • افتح لوحة الخصوصية'}</Text></View>
      <Ionicons name="chevron-back" size={20} color={theme.muted}/>
    </Pressable>
  </>;
}
const s=StyleSheet.create({row:{flexDirection:'row-reverse',gap:10},card:{flex:1,minHeight:108,borderRadius:24,borderWidth:1,padding:14,flexDirection:'row-reverse',alignItems:'center',gap:10},icon:{width:44,height:44,borderRadius:15,borderWidth:1,alignItems:'center',justifyContent:'center'},copy:{flex:1},title:{fontSize:14,fontWeight:'900',textAlign:'right'},sub:{fontSize:10,marginTop:4,textAlign:'right',lineHeight:15},privacy:{minHeight:94,borderRadius:24,borderWidth:1,padding:14,flexDirection:'row-reverse',alignItems:'center',gap:11},shield:{width:46,height:46,borderRadius:15,borderWidth:1,alignItems:'center',justifyContent:'center'},privacyTitleRow:{flexDirection:'row-reverse',alignItems:'center',justifyContent:'space-between',gap:8},privacyTitle:{fontSize:15,fontWeight:'900',textAlign:'right',flexShrink:1},privacySub:{fontSize:10,marginTop:6,textAlign:'right',lineHeight:16},statePill:{height:25,borderRadius:10,borderWidth:1,paddingHorizontal:7,flexDirection:'row-reverse',alignItems:'center',gap:5},dot:{width:6,height:6,borderRadius:3},stateText:{fontSize:8.5,fontWeight:'900'},press:{transform:[{scale:.985}],opacity:.84}});
