import { Pressable, StyleSheet, Text, View } from 'react-native';
import type { ThemePalette } from '@/lib/theme';

export function HomeFeatureCards({theme,downloadsCount,onDownloads,onLibrary,onPrivacy}:{theme:ThemePalette;downloadsCount:number;onDownloads:()=>void;onLibrary:()=>void;onPrivacy:()=>void}){
  const card=(title:string,sub:string,tone:string,onPress:()=>void,icon:string)=><Pressable onPress={onPress} style={({pressed})=>[s.card,{backgroundColor:tone,borderColor:theme.border},pressed&&s.press]}><View style={s.icon}><Text style={s.iconText}>{icon}</Text></View><View style={s.copy}><Text style={s.title}>{title}</Text><Text style={s.sub}>{sub}</Text></View><Text style={s.arrow}>‹</Text></Pressable>;
  return <>
    <View style={s.row}>{card('التنزيلات',downloadsCount?`${downloadsCount} عناصر حديثة`:'إدارة ملفاتك','#3A4650',onDownloads,'↓')}{card('المفضلة','وصول سريع','#51493F',onLibrary,'★')}</View>
    <Pressable onPress={onPrivacy} style={({pressed})=>[s.privacy,{backgroundColor:theme.surface,borderColor:theme.border},pressed&&s.press]}><View style={s.shield}><Text style={s.shieldText}>✓</Text></View><View style={s.copy}><Text style={[s.privacyTitle,{color:theme.text}]}>حماية الخصوصية</Text><Text style={[s.privacySub,{color:theme.muted}]}>HTTPS وVPN وبيانات التصفح في مكان واحد</Text></View><Text style={[s.arrow,{color:theme.muted}]}>‹</Text></Pressable>
  </>;
}
const s=StyleSheet.create({row:{flexDirection:'row-reverse',gap:10},card:{flex:1,minHeight:104,borderRadius:24,borderWidth:1,padding:14,flexDirection:'row-reverse',alignItems:'center',gap:10},icon:{width:44,height:44,borderRadius:15,backgroundColor:'rgba(255,255,255,.12)',alignItems:'center',justifyContent:'center'},iconText:{color:'#FFF',fontSize:20,fontWeight:'900'},copy:{flex:1},title:{color:'#FFF',fontSize:14,fontWeight:'900',textAlign:'right'},sub:{color:'#E3DDD7',fontSize:10,marginTop:4,textAlign:'right'},arrow:{color:'#FFF',fontSize:28,fontWeight:'300'},privacy:{minHeight:88,borderRadius:24,borderWidth:1,padding:14,flexDirection:'row-reverse',alignItems:'center',gap:11},shield:{width:46,height:46,borderRadius:15,backgroundColor:'#DFF3E7',alignItems:'center',justifyContent:'center'},shieldText:{color:'#2F9E63',fontSize:22,fontWeight:'900'},privacyTitle:{fontSize:16,fontWeight:'900',textAlign:'right'},privacySub:{fontSize:11,marginTop:4,textAlign:'right'},press:{transform:[{scale:.985}],opacity:.86}});
