import { useState } from 'react';
import { Pressable, SafeAreaView, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { signIn, signUp } from '@/lib/auth';

export default function LoginScreen(){
  const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [mode,setMode]=useState<'signin'|'signup'>('signin'); const [msg,setMsg]=useState(''); const [busy,setBusy]=useState(false);
  const submit=async()=>{setBusy(true);setMsg('');try{if(mode==='signin') await signIn(email.trim(),password); else await signUp(email.trim(),password); setMsg(mode==='signin'?'تم تسجيل الدخول':'تم إنشاء الحساب. تحقق من بريدك إذا كان التأكيد مفعلاً.'); if(mode==='signin') setTimeout(()=>router.replace('/'),400);}catch(e){setMsg(e instanceof Error?e.message:'Authentication error');}finally{setBusy(false)}};
  return <SafeAreaView style={s.root}><View style={s.box}><Text style={s.brand}>RAID ACCOUNT</Text><Text style={s.desc}>حساب واحد للمزامنة والـ AI Agent والإعدادات.</Text><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="البريد الإلكتروني" placeholderTextColor="#64748B" style={s.input}/><TextInput value={password} onChangeText={setPassword} secureTextEntry placeholder="كلمة المرور" placeholderTextColor="#64748B" style={s.input}/><Pressable onPress={submit} disabled={busy} style={s.primary}><Text style={s.primaryText}>{busy?'...':mode==='signin'?'تسجيل الدخول':'إنشاء حساب'}</Text></Pressable><Pressable onPress={()=>setMode(mode==='signin'?'signup':'signin')}><Text style={s.link}>{mode==='signin'?'ليس لديك حساب؟ إنشاء حساب':'لديك حساب؟ تسجيل الدخول'}</Text></Pressable>{!!msg&&<Text style={s.msg}>{msg}</Text>}<Pressable onPress={()=>router.back()}><Text style={s.back}>رجوع</Text></Pressable></View></SafeAreaView>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#070B14',justifyContent:'center',padding:20},box:{backgroundColor:'#111827',borderWidth:1,borderColor:'#27324A',borderRadius:28,padding:22,gap:14},brand:{fontSize:28,fontWeight:'900',color:'#fff',letterSpacing:2},desc:{color:'#94A3B8',lineHeight:20,textAlign:'right'},input:{height:52,borderRadius:16,backgroundColor:'#0B1220',borderWidth:1,borderColor:'#27324A',paddingHorizontal:14,color:'#fff',textAlign:'right'},primary:{height:52,borderRadius:16,alignItems:'center',justifyContent:'center',backgroundColor:'#7C3AED'},primaryText:{color:'#fff',fontWeight:'900'},link:{color:'#A78BFA',textAlign:'center',fontWeight:'700'},msg:{color:'#CBD5E1',textAlign:'center'},back:{color:'#94A3B8',textAlign:'center'}});
